apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace | default "default" | quote }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.labels }}
      {{ $key }}: {{ quote $value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ quote $value }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.version }}"
          ports:
            {{- range .Values.deployment.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          volumeMounts:
            {{- range .Values.deployment.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
      volumes:
        {{- range .Values.deployment.volumes }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap.name }}
        {{- end }}