apiVersion: v1
kind: Namespace
metadata: 
  name: {{ .Values.namespace | default "default" | quote }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
